version: '3.10'

services:
  car-park-backend:
    container_name: car-park-backend
    build:
      context: ../../
      dockerfile: deploy/prod/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - car-park-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  car-park-network:
    driver: bridge

volumes:
  fastapi:
    driver: local
