name: CI/CD to EC2

# trigger only on pushes to main (or change to your prod branch)
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy on EC2
        with:
          host: ${{secrets.EC2_SSH_HOST}}
          username: ${{secrets.EC2_SSH_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            cd /home/ec2-user/nsw-carpark-finder/deploy/prod
            git pull origin main
            docker-compose -f docker-compose.prod.yaml down || true
            docker rmi prod-car-park-backend || true
            docker-compose -f docker-compose.prod.yaml up -d
          
